# Generated by Django 3.1.1 on 2020-09-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('uid_name', models.CharField(max_length=800)),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
